/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joaob
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */

    public JFrame() {
        initComponents();
        FalaLabel.setText("<html>O Génio pensou num número de 1 a 100! Tente adivinhar!</html>");
      
    }
        double n = 1 + Math.random() * (101-1);
        int valor = (int) n;
        int numTentativas = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GenioLabel = new javax.swing.JLabel();
        FalaLabel = new javax.swing.JLabel();
        BalaoFalaLabel = new javax.swing.JLabel();
        PalpiteButton = new javax.swing.JButton();
        NumSpinner = new javax.swing.JSpinner();
        ResultadoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GenioLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genio-della-lampada-png.png"))); // NOI18N
        GenioLabel.setText("jLabel2");
        jPanel1.add(GenioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 256, -1));

        FalaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FalaLabel.setForeground(new java.awt.Color(255, 255, 255));
        FalaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FalaLabel.setText("jLabel3");
        jPanel1.add(FalaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, 100));

        BalaoFalaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat.png"))); // NOI18N
        BalaoFalaLabel.setText("jLabel1");
        jPanel1.add(BalaoFalaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 256, -1));

        PalpiteButton.setBackground(new java.awt.Color(102, 153, 255));
        PalpiteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PalpiteButton.setForeground(new java.awt.Color(51, 51, 51));
        PalpiteButton.setText("Palpite");
        PalpiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalpiteButtonActionPerformed(evt);
            }
        });
        PalpiteButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PalpiteButtonKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PalpiteButtonKeyTyped(evt);
            }
        });
        jPanel1.add(PalpiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        NumSpinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NumSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jPanel1.add(NumSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 70, 40));

        ResultadoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(ResultadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 190, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PalpiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalpiteButtonActionPerformed
        // TODO add your handling code here:
        numTentativas = numTentativas + 1;
        
       
        
        int numPalpite = Integer.parseInt(NumSpinner.getValue().toString());
        
        if(numPalpite == valor){
        
            if(numTentativas == 1){
                ResultadoLabel.setText("<html>Acertou!!! Apenas necessitou de " + numTentativas + " tentativa!</html>");
            }
            else{
                ResultadoLabel.setText("<html>Acertou!!! Apenas necessitou de " + numTentativas + " tentativas!</html>");
            }
        }
        else if(numPalpite > valor){
            ResultadoLabel.setText("<html>Palpite muito alto! Tente baixar um pouco...</html>");
        }
        else if(numPalpite < valor){
            ResultadoLabel.setText("<html>Palpite muito baixo! Tente subir um pouco...</html>");
        }
        
        
        
    }//GEN-LAST:event_PalpiteButtonActionPerformed

    private void PalpiteButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PalpiteButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalpiteButtonKeyPressed

    private void PalpiteButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PalpiteButtonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PalpiteButtonKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalaoFalaLabel;
    private javax.swing.JLabel FalaLabel;
    private javax.swing.JLabel GenioLabel;
    private javax.swing.JSpinner NumSpinner;
    private javax.swing.JButton PalpiteButton;
    private javax.swing.JLabel ResultadoLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
